
import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import PageHeader from '@/components/common/PageHeader';
import ControlPanel from '@/components/common/ControlPanel';
import ResultPanel from '@/components/common/ResultPanel';
import { Button } from '@/components/ui/button';
import { Download, Upload } from 'lucide-react';

export default function UploadDownloadPage() {
  const [fileInfo, setFileInfo] = useState(null);

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setFileInfo({
        name: file.name,
        size: (file.size / 1024).toFixed(2) + ' KB',
        type: file.type
      });
    }
  };

  const handleDownloadText = () => {
    const text = 'This is a sample text file generated by UI Practice Hub';
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sample.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <Helmet>
        <title>Upload & Download - UI Practice Hub</title>
        <meta name="description" content="Practice file upload and download" />
      </Helmet>

      <PageHeader title="Upload & Download" subtitle="Practice file operations" />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6" data-testid="page-upload-download-container">
        <ControlPanel title="File Operations">
          <div className="space-y-4">
            <div>
              <label htmlFor="fileUpload" className="block text-sm font-medium mb-2">
                Upload File
              </label>
              <input
                type="file"
                id="fileUpload"
                onChange={handleFileChange}
                className="w-full text-sm file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-primary file:text-primary-foreground hover:file:bg-primary/90"
                data-testid="input-file-upload"
              />
            </div>
            <div>
              <Button onClick={handleDownloadText} className="w-full gap-2" data-testid="button-download-sample">
                <Download className="h-4 w-4" />
                Download Text File
              </Button>
            </div>
          </div>
        </ControlPanel>

        <ResultPanel title="File Information">
          {fileInfo ? (
            <div className="space-y-2" data-testid="file-info-display">
              <p><strong>Name:</strong> {fileInfo.name}</p>
              <p><strong>Size:</strong> {fileInfo.size}</p>
              <p><strong>Type:</strong> {fileInfo.type || 'Unknown'}</p>
            </div>
          ) : (
            <p className="text-muted-foreground" data-testid="text-no-file">No file uploaded</p>
          )}
        </ResultPanel>
      </div>
    </>
  );
}
